server:
  port: 30000


spring:
  main:
    lazy-initialization: true
  application:
    name: tech-spring
  profiles:
    active: default
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  data:
    redis:
      host: 1.116.14.13
      connect-timeout: 10000
      port: 6379
      password: toor
  cache:
    type: redis



logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){cyan} %clr([TRACEID:%X{traceId}]){faint} %clr([%t]){magenta} %clr(${LOG_LEVEL_PATTERN:%p}) %clr(%logger){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} [TRACEID:%X{traceId}] [%t] ${LOG_LEVEL_PATTERN:%p} %logger [lineno:%line]: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error
    vip.corejava.app.client: debug
  file:
    name: ./target/log/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 20
      max-history: 14

feign:
  client:
    config:
      default:
        connectTimeout: 150000
        readTimeout: 150000